__title__ = 'sql_parser'
__package_name__ = 'sql_parser'
__version__ = '0.10.2'
__description__ = "Mindsdb SQL parser"
__email__ = "jorge@mindsdb.com"
__author__ = 'MindsDB Inc'
# __github__ = 'https://github.com/mindsdb/mindsdb.sql_parser'
# __pypi__ = 'https://pypi.org/project/mindsdb.sql_parser'
__license__ = 'MIT'
__copyright__ = 'Copyright 2024- mindsdb'
