__title__ = 'MindsDB Microsoft SQL Server handler with Polars'
__package_name__ = 'mindsdb_mssql_handler'
__version__ = '0.0.1'
__description__ = "MindsDB handler for Microsoft SQL Server with Polars"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/mindsdb'
__pypi__ = 'https://pypi.org/project/mindsdb/'
__license__ = 'MIT'
__copyright__ = 'Copyright 2022- mindsdb'
