"""empty message

Revision ID: f2712bdf474b
Revises: 608e376c19a7
Create Date: 2025-07-23 16:55:51.761237

"""
from alembic import op
import sqlalchemy as sa
import mindsdb.interfaces.storage.db  # noqa



# revision identifiers, used by Alembic.
revision = 'f2712bdf474b'
down_revision = '608e376c19a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('ending_time', sa.Time(), nullable=True))

    with op.batch_alter_table('meta_columns', schema=None) as batch_op:
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('meta_tables', schema=None) as batch_op:
        batch_op.alter_column('integration_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_tables', schema=None) as batch_op:
        batch_op.alter_column('integration_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('meta_columns', schema=None) as batch_op:
        batch_op.alter_column('table_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('ending_time')
        batch_op.drop_column('starting_time')

    # ### end Alembic commands ###
